# Generated by Django 4.0.4 on 2022-04-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinUser',
            new_name='LibUser',
        ),
    ]
